### PR TITLE
Login page logo

### PR DESCRIPTION
**Pull request by MohitKochar**

### CODE REVIEW

**Comment by MohitKochar** [comment]
check it @monsij

**Comment by monsij** [comment]
Capture
Currently it appears as this. To center this properly, image cropping may also be required. 
_**Make changes in this PR itself and include screenshot after you are done.**_

**Comment by ZER-0-NE** [comment]
Include a screenshot @MohitKochar

**Comment by MohitKochar** [comment]
I'm doing it but aspect ratio is not maintaining @ZER-0-NE

**Comment by ZER-0-NE** [comment]
Include a ss so that we can take a look

**Comment by MohitKochar** [comment]
ok

**Comment by MohitKochar** [comment]
IMG20190607160005
IMG20190607160013

**Comment by MohitKochar** [comment]
check it @ZER-0-NE

**Comment by ZER-0-NE** [comment]
try to make it responsive to windows size changes then @MohitKochar

**Comment by MohitKochar** [comment]
now check it @ZER-0-NE and @monsij

**Pull request closed without merging**
